### PR TITLE
Add a section to point people to shared lab resources

### PR DESCRIPTION
**Pull request by ahart1**

### CODE REVIEW

**Comment by ahart1** [comment]
Finish adding section to lab manual to point users to shared lab resources

**Comment by ahart1** [comment]
I accidentally closed this, but it still needs to be merged with main branch of lab-manual

**Comment by ahart1** [comment]
Finish adding section for real this time.

**Comment by gavinfay** [comment]
@gavinfay needs to re-render the book based on these changes by @ahart1.

**Pull request merged**
