### PR TITLE
Openscapes Update Merge Request 

### PR DESCRIPTION
**Pull request by IleanaF**

### CODE REVIEW

**Review by stefaniebutland — APPROVED** [review]
Thank you so much @IleanaF for your work on this!

I'm merging this pull request and then @jules32 will make final edits to the GitHub Action that renders the book.

**Comment by gavinfay** [comment]
Thank you thank you @IleanaF for your amazing work on this! Thank you @stefaniebutland & @jules32 also! 
🚀

**Comment by jules32** [comment]
Woohoo! Merging, and then will check and update the GitHub Action :)

**Comment by jules32** [comment]
Yay @gavinfay @IleanaF @stefaniebutland it's all updated and working, published with the updated github action!

Gavin there's obviously a lot more stylizing goodies to explore and we can share tips as we learn them too. Great job @IleanaF ! 🎉

**Comment by gavinfay** [comment]
Brilliant! 🙌

**Pull request merged**
